# Case_1
#developers: Pokareva Christina (55%)
#            Pestretsova Margarita (25%)
#            Vasilevsky Egor (50%)
import turtle

    #TODO: (Yegor-Vasilevskii) 2 фигуры
 #fig 1
import turtle
win = turtle.Screen()
turtle.shape('turtle')
turtle.speed(0)

turtle.penup()
turtle.goto(-200,200)
turtle.pendown()
turtle.write('Фигура 1')

turtle.penup()
turtle.goto(-330,180)
turtle.pendown()
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.penup()
turtle.goto(-290,140)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.forward(140)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(-100,180)
turtle.pendown()
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.penup()
turtle.goto(50,40)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(70)
turtle.end_fill()

turtle.penup()
turtle.goto(140,180)
turtle.pendown()
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.penup()
turtle.goto(215,180)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.forward(70)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.end_fill()

turtle.penup()
turtle.goto(-100,210)
turtle.pendown()
turtle.write('К 140-летию К. Малевича посвящается')


#Fig 2
turtle.penup()
turtle.goto(-200,-120)
turtle.pendown()
turtle.write('Фигура 2')

turtle.penup()
turtle.goto(-20,-110)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(170)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(170)
turtle.end_fill()

turtle.penup()
turtle.goto(45,-145)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(23)
turtle.end_fill()
turtle.penup()
turtle.goto(45,-198)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(23)
turtle.end_fill()
turtle.penup()
turtle.goto(45,-250)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(23)
turtle.end_fill()

#TODO (ChristinaPokareva)

turtle.penup()
turtle.goto(0, 0)
turtle.right(90)
turtle.pendown

win = turtle.Screen()
turtle.shape('arrow')
turtle.speed(0)

turtle.fillcolor ('orange')
turtle.begin_fill()
turtle.right(45)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.forward(5)
turtle.pendown()

turtle.fillcolor ('pink')
turtle.begin_fill()
turtle.forward(141.5)
turtle.left(-135)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.left(135)
turtle.forward(5)
turtle.pendown()

turtle.fillcolor ('green')
turtle.begin_fill()
turtle.forward(170)
turtle.left(45)
turtle.forward(100)
turtle.left (135)
turtle.forward(170)
turtle.left (45)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.back(101)
turtle.right(90)
turtle.forward(5)
turtle.pendown()

turtle.fillcolor ('violet')
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right (135)
turtle.forward(145)
turtle.end_fill()

turtle.penup()
turtle.goto(0,0)
turtle.left (-45)
turtle.forward(145)
turtle.pendown()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.right(90)
turtle.forward(220)
turtle.right(90)
turtle.forward(220)
turtle.right(135)
turtle.forward(311)
turtle.end_fill()

turtle.penup()
turtle.left(45)
turtle.forward(5)
turtle.pendown()

turtle.fillcolor ('red')
turtle.begin_fill()
turtle.forward(220)
turtle.left(90)
turtle.forward(220)
turtle.left(135)
turtle.forward(311)
turtle.end_fill()

turtle.penup()
turtle.left(45)
turtle.forward(5)
turtle.left(-90)
turtle.pendown()

turtle.fillcolor ('blue')
turtle.begin_fill()
turtle.forward(110)
turtle.left(135)
turtle.forward(156)
turtle.left(90)
turtle.forward(156)
turtle.left(135)
turtle.forward(110)
turtle.end_fill()

turtle.penup()

win.exitonclick()

#TODO: (MargaritaPestretsova)

#TODO (StepanDt)

